pipeline:
  publish-docker-image---latest:
    image: plugins/docker:17.12
    registry: docker.io
    group: publish
    repo: docker.io/kkrampa/s3-uploader-api
    secrets: [ docker_username, docker_password ]
    label_schema:
    - ci-build-number=${DRONE_BUILD_NUMBER}
    - vcs-commit-branch=${DRONE_COMMIT_BRANCH}
    - vcs-commit-sha=${DRONE_COMMIT_SHA}
    tags:
    - latest
    - ${DRONE_BUILD_NUMBER}
    - ${DRONE_COMMIT_SHA}
    when:
      event: [ push ]
      branch: [ master ]
  